# Generated by Django 4.0.4 on 2022-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_profile_profilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilenumber',
            field=models.CharField(default='', max_length=122),
        ),
    ]
